- hosts: all 
  tasks:
  - name: Count process running in remote systems
    shell: ps | wc -l
    register: remote_processes_number
  - name: Print remote running procss
    debug: 
      msg: '{{ remote_processes_number.stdout }}'
  - name:  count process running in local system
    shell: ps | wc -l
    delegate_to: localhost
    register: local_processes_number
  - name: Print local running processes
    debug:
      msg: '{{ local_processes_number.stdout }}'
